zoom: 2
url_path_prefix: /python_maproom

# DB configuration for the production docker environment. Override in
# development environment.
db:
    host: postgres
    port: 5432
    user: ingrid
    dbname: iridb

maprooms:

    flex_fcst:

        # App set up
        - title: flex_cst_precip
          core_path: flex_fcst_precip
          forecast_path: /Data/data21/iri/FD.3
          variable: Precipitation
          y_transform: False
          method: elr # or pycpt
          var: precip
          issue_format: "%b %Y"