zoom: 7

datasets:
    shapes_adm:
        - name: Pays
          color: black
          sql: select id_0 as key, name_0 as label, ST_AsBinary(the_geom) as the_geom
                  from sen_adm0
          is_checked: False
        - name: Regions
          color: black
          sql: select id_1 as key, name_1 as label, ST_AsBinary(the_geom) as the_geom
              from sen_adm1
          is_checked: True

maprooms:

    flex_fcst:
      - y_transform: false
        variable: Precipitation
        #Use one or the other to test the nc multiple/single cases
        forecast_path: /data/remic/mydatafiles/ANACIM/cpt_demo/UCSBV3
        #forecast_path: /data/remic/mydatafiles/ANACIM/cpt_demo/UCSBV3/Jul-Sep
        title: flex_cst_precip
        core_path: flex_fcst_precip
        method: pycpt # or pycpt or elr
        var: precip
        issue_format: "%b-%Y"
