name: dash3_geo_pepsico_env
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0
  - aom=3.9.1
  - attrs=25.4.0
  - blinker=1.9.0
  - blosc=1.21.6
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - certifi=2025.11.12
  - click=8.3.1
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - ffmpeg=7.1.1
  - flask=3.1.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - freexl=2.0.0
  - fribidi=1.0.16
  - gdk-pixbuf=2.44.4
  - geos=3.14.0
  - geotiff=1.7.4
  - giflib=5.2.2
  - gmp=6.3.0
  - graphite2=1.3.14
  - harfbuzz=12.2.0
  - hdf5=1.14.6
  - icu=75.1
  - imath=3.1.12
  - importlib-metadata=8.7.0
  - itsdangerous=2.2.0
  - jasper=4.2.8
  - jinja2=3.1.6
  - json-c=0.18
  - krb5=1.21.3
  - lame=3.100
  - lerc=4.0.0
  - libabseil=20250127.1
  - libaec=1.1.4
  - libarchive=3.8.1
  - libasprintf=0.25.1
  - libass=0.17.3
  - libavif16=1.3.0
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcurl=8.17.0
  - libcxx=21.1.6
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgdal-core=3.10.3
  - libgettextpo=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.2
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.25.1
  - libjpeg-turbo=3.1.2
  - libkml=1.3.0
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopencv=4.11.0
  - libopenvino=2025.0.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-intel-cpu-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopus=1.5.2
  - libpng=1.6.51
  - libpq=18.1
  - libprotobuf=5.29.3
  - librsvg=2.58.4
  - librttopo=1.1.0
  - libspatialite=5.1.0
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libusb=1.0.29
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=21.1.6
  - lz4-c=1.10.0
  - lzo=2.10
  - markupsafe=3.0.3
  - minizip=4.0.10
  - ncurses=6.5
  - numpy=2.3.5
  - opencv=4.11.0
  - openexr=3.3.5
  - openh264=2.6.0
  - openldap=2.6.10
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - pango=1.56.4
  - pcre2=10.46
  - pip=25.3
  - pixman=0.46.4
  - proj=9.6.2
  - psycopg2=2.9.10
  - pugixml=1.15
  - py-opencv=4.11.0
  - pyparsing=3.2.5
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pyyaml=6.0.3
  - rasterio=1.4.3
  - rav1e=0.7.1
  - readline=8.2
  - sdl2=2.32.56
  - sdl3=3.2.26
  - setuptools=80.9.0
  - shapely=2.1.2
  - six=1.17.0
  - snappy=1.2.2
  - snuggs=1.4.7
  - sqlite=3.51.0
  - svt-av1=3.0.2
  - tbb=2022.3.0
  - tk=8.6.13
  - tzdata=2025b
  - uriparser=0.9.8
  - werkzeug=3.1.3
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xarray=2025.11.0
  - xerces-c=3.2.5
  - yaml=0.2.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - cachelib==0.13.0
      - charset-normalizer==3.4.4
      - colorcet==3.1.0
      - dash==3.2.0
      - dash-bootstrap-components==2.0.4
      - dash-extensions==2.0.4
      - dash-leaflet==1.1.3
      - dash-svg==0.0.12
      - dataclass-wizard==0.35.1
      - editorconfig==0.17.1
      - flask-caching==2.3.1
      - geobuf==2.0.0
      - idna==3.11
      - jsbeautifier==1.15.4
      - more-itertools==10.8.0
      - narwhals==2.12.0
      - nest-asyncio==1.6.0
      - plotly==6.5.0
      - protobuf==6.33.1
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - requests==2.32.5
      - retrying==1.4.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
